config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tags
  resources :topics do
    collection do
      get :form_display , controller: :posts
    end

    resources :posts do
      member do
        get :readstatus
      end
      resources :comments
      resources :ratings
    end
  end

  get "/posts", to: 'posts#index'
  root "topics#index"
  # get '/topics/:topic_id/posts/:id/readstatus' => 'posts#readstatus'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #header for sign in
  get "/user", to: "application#authenticate"

  # resources :device , only: [:device_detect] , path ""do
  #   collection do
  #     get :device_detect , path: '/device'
  #   end
  get "/device", to: "device#device_detect"
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts , dependent: :destroy

  validates :name,presence:true ,length: { minimum: 3,maximum: 15,  message: "name should be of length 3 to 15 character" }

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
   # protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format =~ %r{application/json} }
  skip_before_action :verify_authenticity_token

  def index
    @topics = Topic.all.paginate(page: params[:page], per_page: 2)
  end

  def show
    @post = @topic.posts.includes(:user).paginate(page: params[:page], per_page: 5)
  end


  def new
    @topic = Topic.new
  end

  def edit
  end

  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @topic.destroy
        format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
        format.json {render json: {"message": "Topic was successfully destroyed."} }
      else
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_topic
    @topic = Topic.find(params[:id])
  end

  def topic_params
    params.require(:topic).permit(:name)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic, authenticity_token: true do |form| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic ,class: "btn btn-success" %> |
<%= link_to 'Back', topics_path ,class: "btn btn-danger"%>

app/views/topics/index.html.erb
<h1>Topics</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |(topic,name)| %>
      <tr>
        <td><%= name %></td>
        <td><%= link_to 'Show', topic_path(topic) ,class: 'btn btn-dark' %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) , class: 'btn btn-primary'%></td>
        <td><%= link_to 'Destroy', topic_path(topic), method: :delete,  class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'posts', topic_posts_path(topic), class: 'btn btn-success' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  <%= link_to 'New Topic', new_topic_path , remote: true ,id: "new_topic",class: 'btn btn-secondary'%>

<%= will_paginate @topics,renderer: BootstrapPagination::Rails %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/new.js.erb
$('#new_topic').hide().after('<%= j render("form") %>');

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<% if @topic.posts.present? %>
      <h1>Posts</h1>

      <table class="table table-bordered">
        <thead>
        <tr>
          <th><h1>name</h1></th>

        </tr>
        </thead>

        <tbody>
        <% @post.each do |post| %>
           <tr> <td><h4><%= post.title %></h4>
              <p><% if current_user.posts.include?(post) %>
                 <span style="color:lawngreen;">read </span>
              <% else %>
                <span style="color:orangered;">unread</span>
              <% end %></p>
                </td>
            <td><%= link_to 'Show', topic_post_path(post.topic_id,post) , class: "btn btn-success" %></td>
          <% if can? :update , post %>
            <td><%= link_to 'Edit', topic_post_path(post.topic_id,post) , class: "btn btn-primary" %></td>
            <td><%= link_to 'Destroy', topic_post_path(post.topic_id,post), method: :delete, class: "btn btn-destroy", data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <% end %>
        <% end %>

        </tbody>
      </table>
  <%#= #will_paginate @topic.posts,renderer: BootstrapPagination::Rails %>
  <% else %>
       <h1> no post in the topic </h1>
  <% end %>

<br>
<%  if !params[:topic_id].blank? %>
  <%= link_to 'New Post',  new_topic_post_path %></button>

<% end %>
<%= link_to 'Back',  topics_path , class: "btn btn-primary"%>