config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tags
  resources :topics do
    collection do
      get :form_display , controller: :posts
    end

    resources :posts do
      member do
        get :readstatus
      end
      resources :comments
      resources :ratings
    end
  end

  get "/posts", to: 'posts#index'
  root "topics#index"
  # get '/topics/:topic_id/posts/:id/readstatus' => 'posts#readstatus'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #header for sign in
  get "/user", to: "application#authenticate"

  # resources :device , only: [:device_detect] , path ""do
  #   collection do
  #     get :device_detect , path: '/device'
  #   end
  get "/device", to: "device#device_detect"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments,  dependent: :destroy
  has_many :ratings , dependent: :destroy
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :users


  accepts_nested_attributes_for :tags, reject_if: -> (tag) {tag['tag'].blank?}

  validates :title,presence:true ,length: { minimum: 3,maximum: 15,  message: "title should be of length 3 to 20 character" }
  validates :body,presence:true ,length: { minimum: 4,maximum: 100,  message: "body should be of length 4 to 100 character" }

  has_attached_file :image , styles: { medium: "300x300>", thumb: "100x100#" }
  validates_attachment_content_type :image , content_type: /\Aimage\/.*\z/
  scope :date_of_post, ->(post_from,post_to) { where(created_at: post_from..post_to)}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_topic
  before_action :set_post, only: [:show, :edit, :destroy, :update]
  # before_action :authorize_resource, only: [:update, :destroy, :edit ]
  load_and_authorize_resource except: [:read_status , :index , :show]

  def index
    if params[:topic_id].blank?
      @posts = Post.all.paginate(page: params[:page], per_page: 5).includes(:topic ,:user )
    else
      @posts = @topic.posts.all.paginate(page: params[:page], per_page: 5).includes(:user)
    end
  end

  def form_display
    if params[:date_to] < params[:date_from]
      respond_to do |format|
        format.html
        format.js
      end
    else
      @sp= Post.all.paginate(page: params[:page], per_page: 5).date_of_post(params[:date_from],params[:date_to])
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def show
    @comments =@post.comments.all.eager_load(:user)
    @comment = @post.comments.new
    @rating = @post.ratings.all
    @group_rating = @rating.order(:rating).group(:rating).count
    @tag=Tag.all
  end

  def new
    @post = @topic.posts.new
  end

  def edit
  end

  def create
    @post = @topic.posts.create(post_params.merge(user_id: current_user.id))
    respond_to do |format|
      if @post.save
        format.html { redirect_to topic_posts_path }
        format.js
      else
        format.html { render :new, notice:"fgfhgf" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def readstatus
    respond_to do |format|
      unless @post.users.include?(current_user)
        @post.users << current_user
      end
      format.js
    end
  end
  def update
    respond_to do |format|
      if @post.update(post_params.merge(user_id: current_user.id))
        format.html { redirect_to topic_posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy

    respond_to do |format|
      if @post.destroy
        format.html { redirect_to topic_posts_path, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end

    end
  end

  private
  def set_topic
    unless params[:topic_id].blank?
      @topic = Topic.find(params[:topic_id])
    end
  end

  def set_post
    @post = @topic.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title ,:body ,:image , tags_attributes: [:tag], tags: :tag )
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_date.html.erb
<nav class="navbar navbar">
  <a class="navbar-brand" href="/">Select post</a>
  <%= form_with url:form_display_topics_path ,remote: true, method: 'get' do |f|%>
    <label> from_date </label> <%= date_field_tag(:date_from ,Date.yesterday,class:"date") %>
    <label> to_date </label> <%= date_field_tag(:date_to ,Date.today,class:"date") %>
    <%= f.submit "show details" %>
  <% end %>
</nav>

app/views/posts/_form.html.erb
<%= form_for [@topic,@post],remote: true, html: { multipart: true } do |form| %>

  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>


  <%= form.fields_for :tags ,@post.tags.build do |ff| %>
    <%= ff.label :tag %>
    <%= ff.text_area :tag %>
  <% end %>

  <%= form.collection_select(:tags, Tag.all, :id, :tag, {}, {multiple: true}) %>

  <div class="actions">
    <%= form.submit(data: { disable_with: 'Saving!!!!!!!!' })
    %>
  </div>

<% end %>

app/views/posts/_form_display.html.erb
<tbody>
<td><h4><%= post.title %> (<%= post.topic .name %>)</h4>
  <% if current_user.posts.include?(post) %>
    <p style="color:lawngreen;">read </p>
  <% else %>
    <p style="color:orangered;">unread</p>
  <% end %></td>
<td><%= link_to 'Show', topic_post_path(post.topic_id,post) , class: "btn btn-success" %></td>
<% if can? :update , post %>
  <td><%= link_to 'Edit', topic_post_path(post.topic_id,post) , class: "btn btn-primary" %></td>
<% end %>
<% if can? :destroy , post %>
  <td><%= link_to 'Destroy', topic_post_path(post.topic_id,post), method: :delete,remote: true, class: "btn btn-destroy", data: { confirm: 'Are you sure?' } %></td>
<% end %>
<td><%= link_to 'comments', topic_post_comments_path(post.topic_id,post) , class: "btn btn-primary" %></td>
</h5>
</tbody>

app/views/posts/create.js.erb
$('#error_explanation').remove();
<% if not @post.errors.any? %>
  $('#new_post').empty();
  $("#new_link").show();
  alert("post created sucessfully");
<% else %>
  $('#error-page').prepend("<%= j render(partial: 'layouts/error_display', locals: { error: @post }) %>")
<% end %>

app/views/posts/destroy.js.erb
alert("Post destroyed");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>


<%= link_to 'Show', topic_post_path ,class: "btn btn-success"%> |
<%= link_to 'Back', topic_post_path ,class: "btn btn-danger" %>

app/views/posts/form_display.js.erb
$('#exist').empty();
$('#xzy').empty();
<% if params[:date_to] > params[:date_from] %>
$spost = ''
<% @sp.each do |f|%>
$spost += '<%= j render(:partial => "posts/form_display",locals: {post:f}) %>';
<% end %>
$('#xzy').html($spost);
$('#paginate').html('<%= j will_paginate @sp, renderer: BootstrapPagination::Rails %>');
$('.pagination a').attr('data-remote', 'true');
<% else %>
$("#date_from").attr('style', "border-radius: 1px; border:#FF0000 1px solid;");
$("#date_to").attr('style', "border-radius: 1px; border:#FF0000 1px solid;");
$('#xzy').html("<h2> date is out of range </h2>")
alert("date out of range")
<% end %>

app/views/posts/index.html.erb
<%= render(partial:'date') %>


<h1>Posts</h1>

<div id="error-page"></div>

<table id="xzy"></table>
<div id ="paginate"></div>
<div id="exist">
<%  if !params[:topic_id].blank? %>
  <%= link_to 'New_Post',  new_topic_post_path(params[:topic_id]) , remote: true ,id: "new_link",  class: "btn btn-danger" %>
<% end %>

<table class="table table-bordered">
  <thead>
  <tr>
    <th><h1>name</h1></th>

  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
        <%= render(partial: "posts/form_display",locals: {post: post}) %>
<!--    <td><h4><%#= post.title %> (<%#= post.topic .name %>)</h4>-->
      <%# if current_user.posts.include?(post) %>
<!--        <p style="color:lawngreen;">read </p>-->
      <%# else %>
<!--        <p style="color:orangered;">unread</p>-->
<!--      <%# end %></td>-->
<!--    <td><%#= link_to 'Show', topic_post_path(post.topic_id,post) , class: "btn btn-success" %></td>-->
    <%# if can? :update , post %>
<!--      <td><%#= link_to 'Edit', topic_post_path(post.topic_id,post) , class: "btn btn-primary" %></td>-->
    <%# end %>
    <%# if can? :destroy , post %>
<!--      <td><%#= link_to 'Destroy', topic_post_path(post.topic_id,post), method: :delete, class: "btn btn-destroy", data: { confirm: 'Are you sure?' } %></td>-->
    <%# end %>
<!--    <td><%#= link_to 'comments', topic_post_comments_path(post.topic_id,post) , class: "btn btn-primary" %></td>-->
<!--    </h5></tr>-->
  <% end %>

  </tbody>
</table>


<br>
<%= will_paginate @posts,renderer: BootstrapPagination::Rails %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', topic_posts_path %>

app/views/posts/new.js.erb
$('#new_link').hide();
$('#new_post').html('<div class="jumbotron"><%= j render("form") %></div>');

app/views/posts/readstatus.js.erb
$('#status-report').html('<p style="color:lawngreen;">read</p>').notify("Access granted", "success");

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12" >
      <p id="notice"><%= notice %></p>

      <p>
      <h1> <strong>Name:</strong></h1><h3><%= @post.title %></h3>
      <div id="status-report"><p style="color:orangered;">unread</p></div>
      </p>
      <%= @post.body %>
      </p>

      <% if can? :update, @post %>
        <%= link_to 'Edit', edit_topic_post_path, class:"btn btn-danger" %> </button>
      <% end %>
      <%= link_to 'Back',"javascript:history.back()",class: "btn btn-warning" %></button>
    </div>
  </div>


  <p id="notice"><%= notice %></p>
  <%= image_tag @post.image.url(:medium) %>
  <br>
  <strong>tag</strong><br>
  <% @post.tags.each do |tag|%>
<!--      <p><%#= tag.checkbox :tag ,tag.tag %><br></p>-->
    <%= tag.tag %>
  <% end %>

  <%= render 'ratings/form' , rating:@rating %>

  <strong>Rating:</strong>

  <%@group_rating.each do |k,c| %>
    <div class="d-inline rating-block" ><%= k%>- star <%= c %></div>
  <% end %>
  <br>
  <strong>AVG Rating:</strong>
  <% if @post.ratings.present? %>
  <%= @post.ratings.average(:rating).truncate(1) %>
<% else %>
    0
    <% end %>
  <h1>Comments</h1>

  <table>
    <thead>
    <tr>
      <th>Comment</th>
      <th colspan="3"></th>
      <th>body</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', topic_post_comment_path(@topic,@post,comment) %></td>
<!--       <td>  <%#= render 'ratings/form' %> </td>-->
        <td><%= form_with url:topic_post_ratings_path(params[:topic_id],params[:post_id]|| params[:id]) do |f| %>
            <%# (1..5).each do |rating| %>

            <%= hidden_field_tag 'com', comment.id %>
            <%= f.radio_button :rating, 1 %>1

            <%= f.radio_button :rating, 2 %>2

            <%= f.radio_button :rating, 3 %>3

            <%= f.radio_button :rating, 4 %>4

            <%= f.radio_button :rating, 5 %>5

            <%#= rating %>
            <%#= UserCommentRating.create!(user_id :current_user , comment_id :Comment.last , rating_id  :Rating.last) %>

            <%# end %>


            <%= f.submit('Rate') %>
          <% end %></td>
        <% if can? :update , comment %>
        <td><%= link_to 'Edit', edit_topic_post_comment_path(@topic,@post,comment) %></td>-
        <td><%= link_to 'Destroy', topic_post_comment_path(@topic,@post,comment) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
          </tr>
    <% end %>
    </tbody>
  </table>

  <br>

<%#= link_to 'New Comment', new_topic_post_comment_path %>

  <%= render 'comments/form' , comment:@comment %>
  <strong>
    <%=@post.comments.count %>
    comments</strong>
</div>

<%= hidden_field_tag :topic_id, params[:topic_id] %>
<%= hidden_field_tag :post_id, params[:id] %>

<script>
    $( document ).ready(function() {
        $.ajax({
            method: "GET",
            url: '/topics/' + $('#topic_id').val() + '/posts/' + $('#post_id').val() + '/readstatus'
            // url: '/topics/' + $('#topic_id').val() + '/posts/readstatus'
        })
    });
</script>